name: "Terraform Pipeline"

on:
  push:
    branches:
      - test

  pull_request:
    branches:
      - test

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: project_time_machine_git/environment/dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: "17d3e7cc-315a-497d-8057-391ba6ddb25d"
          tenant-id: "59a67c47-bdae-49db-b64f-d0d414647a56"
          subscription-id: "2dd57896-7866-4df4-8c9e-6830338bdf29"
          audience: api://AzureADTokenExchange
          auth-type: SERVICE_PRINCIPAL
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/test'
        run: terraform apply -auto-approve tfplan

      - name: Clean up Plan
        if: always()
        run: rm -f tfplan